meta_product_name: "Shelfie"
meta_title: "Shelfie - Keep control of your kitchen to reduce food waste"
meta_description: "The app to help you better manage your groceries stock while motivating you "
meta_image: "cover.png" # should exist in `app/assets/images/`
